// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/threejs/three-transformcontrols.d.ts
declare namespace THREE {
	class DragControls  {
		constructor(object:Camera, domElement?:HTMLElement);

		enable:boolean;
		object: Object3D;

		on(event:string,handler:any):any;
		off(event:string,handler:any):any;
		setObject(objects:any):void;
		activate():void;
		deactivate():void;
		dispose():void;

	}
}
